# Run Redis and PostgreSQL for testing with a local development server.
# This is used by tox -e run, which starts gafaelfawr in the foreground.

version: "3"
services:
  redis:
    image: "redis:latest"
    hostname: "redis"
    container_name: "redis"
    command:
      - "redis-server"
    ports:
      - "6379:6379"
  postgresql:
    image: "postgres:latest"
    hostname: "postgresql"
    container_name: "postgresql"
    environment:
      POSTGRES_PASSWORD: "INSECURE-PASSWORD"
      POSTGRES_USER: "vo-cutouts"
      POSTGRES_DB: "vo-cutouts"
    ports:
      - "5432:5432"
